# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scott Severance on GitHub
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is Scott Severance's GitHub site. Here you will find information about my
  projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mssever.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mssever

# Build settings
markdown: kramdown

# My stuff:
timezone: America/Chicago
encoding: utf-8
detach: false
